FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /app
COPY protoc-gen-fsgrpc/*.fsproj ./protoc-gen-fsgrpc/
COPY FsGrpc/*.fsproj ./FsGrpc/
RUN (cd protoc-gen-fsgrpc && dotnet restore)
COPY protoc-gen-fsgrpc ./protoc-gen-fsgrpc
COPY FsGrpc ./FsGrpc
RUN (cd protoc-gen-fsgrpc && dotnet publish -c Release -o out)

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build-env /app/protoc-gen-fsgrpc/out .
ENTRYPOINT ["dotnet", "protoc-gen-fsgrpc.dll"]
