name: dotnet package

on:
  pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}.x
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}.x
      - name: Display version
        run: dotnet --version
      - name: Gather projects
        run: rm -f fsgrpc-ci.sln && dotnet new sln -n fsgrpc-ci && dotnet sln fsgrpc-ci.sln add `find . -type f -name '*.fsproj'` --in-root
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-restore --verbosity normal
